import type { Company, Candidate, JobOffer, Application } from "@/types";

// ── Platform-wide Companies ──
export const mockAdminCompanies: Company[] = [
  {
    id: "c1",
    companyName: "Tech Solutions Inc.",
    activityDomain: "IT & Software",
    professionalEmail: "contact@techsolutions.dz",
    phoneNumber: "+213 555 123 456",
    website: "https://techsolutions.dz",
    wilaya: "Algiers",
    postalCode: "16000",
    description: "Leading software development company based in Algiers.",
    documents: {
      commercialRegister: { filename: "RC_TechSolutions_2025.pdf", url: "/docs/rc.pdf", uploadedAt: new Date("2025-06-15") },
      nifDocument: { filename: "NIF_TechSolutions.pdf", url: "/docs/nif.pdf", uploadedAt: new Date("2025-06-15") },
    },
    adminFullName: "Ahmed Benali",
    adminEmail: "ahmed@techsolutions.dz",
    status: "Approved",
    registrationDate: new Date("2025-06-15"),
    approvedDate: new Date("2025-06-18"),
    approvedBy: "admin1",
    jobOffersCount: 3,
    totalApplications: 18,
    acceptedCandidates: 5,
    createdAt: new Date("2025-06-15"),
    updatedAt: new Date("2026-02-10"),
  },
  {
    id: "c2",
    companyName: "Digital Marketing DZ",
    activityDomain: "Marketing",
    professionalEmail: "info@digitalmarketingdz.com",
    phoneNumber: "+213 555 234 567",
    wilaya: "Oran",
    postalCode: "31000",
    description: "Digital marketing agency specializing in social media and SEO.",
    documents: {
      commercialRegister: { filename: "RC_DigitalDZ.pdf", url: "/docs/rc2.pdf", uploadedAt: new Date("2025-08-10") },
      nifDocument: { filename: "NIF_DigitalDZ.pdf", url: "/docs/nif2.pdf", uploadedAt: new Date("2025-08-10") },
    },
    adminFullName: "Karima Mansouri",
    adminEmail: "karima@digitalmarketingdz.com",
    status: "Approved",
    registrationDate: new Date("2025-08-10"),
    approvedDate: new Date("2025-08-13"),
    approvedBy: "admin1",
    jobOffersCount: 1,
    totalApplications: 32,
    acceptedCandidates: 0,
    createdAt: new Date("2025-08-10"),
    updatedAt: new Date("2026-01-20"),
  },
  {
    id: "c3",
    companyName: "HealthCare Plus",
    activityDomain: "Healthcare",
    professionalEmail: "hr@healthcareplus.dz",
    phoneNumber: "+213 555 345 678",
    wilaya: "Constantine",
    postalCode: "25000",
    description: "Network of clinics providing healthcare data analysis.",
    documents: {
      commercialRegister: { filename: "RC_HealthCare.pdf", url: "/docs/rc3.pdf", uploadedAt: new Date("2025-09-01") },
      nifDocument: { filename: "NIF_HealthCare.pdf", url: "/docs/nif3.pdf", uploadedAt: new Date("2025-09-01") },
    },
    adminFullName: "Dr. Samir Boumediene",
    adminEmail: "samir@healthcareplus.dz",
    status: "Approved",
    registrationDate: new Date("2025-09-01"),
    approvedDate: new Date("2025-09-04"),
    approvedBy: "admin1",
    jobOffersCount: 1,
    totalApplications: 18,
    acceptedCandidates: 0,
    createdAt: new Date("2025-09-01"),
    updatedAt: new Date("2026-02-10"),
  },
  {
    id: "c4",
    companyName: "EduTech Algeria",
    activityDomain: "Education",
    professionalEmail: "contact@edutech.dz",
    phoneNumber: "+213 555 456 789",
    wilaya: "Sétif",
    postalCode: "19000",
    description: "E-learning platform serving students across Algeria.",
    documents: {
      commercialRegister: { filename: "RC_EduTech.pdf", url: "/docs/rc4.pdf", uploadedAt: new Date("2025-10-15") },
      nifDocument: { filename: "NIF_EduTech.pdf", url: "/docs/nif4.pdf", uploadedAt: new Date("2025-10-15") },
    },
    adminFullName: "Nadia Belhocine",
    adminEmail: "nadia@edutech.dz",
    status: "Approved",
    registrationDate: new Date("2025-10-15"),
    approvedDate: new Date("2025-10-18"),
    approvedBy: "admin1",
    jobOffersCount: 1,
    totalApplications: 27,
    acceptedCandidates: 1,
    createdAt: new Date("2025-10-15"),
    updatedAt: new Date("2026-02-12"),
  },
  {
    id: "c5",
    companyName: "FinanceAlgeria",
    activityDomain: "Finance",
    professionalEmail: "hr@financealgeria.dz",
    phoneNumber: "+213 555 567 890",
    wilaya: "Algiers",
    postalCode: "16000",
    description: "Fast-growing fintech company in Algeria.",
    documents: {
      commercialRegister: { filename: "RC_FinAlgeria.pdf", url: "/docs/rc5.pdf", uploadedAt: new Date("2025-11-20") },
      nifDocument: { filename: "NIF_FinAlgeria.pdf", url: "/docs/nif5.pdf", uploadedAt: new Date("2025-11-20") },
    },
    adminFullName: "Mehdi Kaci",
    adminEmail: "mehdi@financealgeria.dz",
    status: "Approved",
    registrationDate: new Date("2025-11-20"),
    approvedDate: new Date("2025-11-23"),
    approvedBy: "admin1",
    jobOffersCount: 1,
    totalApplications: 15,
    acceptedCandidates: 0,
    createdAt: new Date("2025-11-20"),
    updatedAt: new Date("2026-02-14"),
  },
  // Pending companies
  {
    id: "c6",
    companyName: "BuildPro Construction",
    activityDomain: "Construction",
    professionalEmail: "admin@buildpro.dz",
    phoneNumber: "+213 555 678 901",
    wilaya: "Annaba",
    postalCode: "23000",
    description: "Construction and infrastructure company specializing in residential and commercial projects.",
    documents: {
      commercialRegister: { filename: "RC_BuildPro_2026.pdf", url: "/docs/rc6.pdf", uploadedAt: new Date("2026-02-10") },
      nifDocument: { filename: "NIF_BuildPro.pdf", url: "/docs/nif6.pdf", uploadedAt: new Date("2026-02-10") },
    },
    adminFullName: "Rachid Ferhat",
    adminEmail: "rachid@buildpro.dz",
    status: "Pending",
    registrationDate: new Date("2026-02-10"),
    jobOffersCount: 0,
    totalApplications: 0,
    acceptedCandidates: 0,
    createdAt: new Date("2026-02-10"),
    updatedAt: new Date("2026-02-10"),
  },
  {
    id: "c7",
    companyName: "TransLog Algeria",
    activityDomain: "Transportation",
    professionalEmail: "info@translog.dz",
    phoneNumber: "+213 555 789 012",
    wilaya: "Blida",
    postalCode: "09000",
    description: "Logistics and transportation solutions across Algeria.",
    documents: {
      commercialRegister: { filename: "RC_TransLog.pdf", url: "/docs/rc7.pdf", uploadedAt: new Date("2026-02-12") },
      nifDocument: { filename: "NIF_TransLog.pdf", url: "/docs/nif7.pdf", uploadedAt: new Date("2026-02-12") },
    },
    adminFullName: "Hichem Toumi",
    adminEmail: "hichem@translog.dz",
    status: "Pending",
    registrationDate: new Date("2026-02-12"),
    jobOffersCount: 0,
    totalApplications: 0,
    acceptedCandidates: 0,
    createdAt: new Date("2026-02-12"),
    updatedAt: new Date("2026-02-12"),
  },
  // Rejected
  {
    id: "c8",
    companyName: "QuickHire SARL",
    activityDomain: "Business & Management",
    professionalEmail: "contact@quickhire.dz",
    phoneNumber: "+213 555 890 123",
    wilaya: "Tlemcen",
    postalCode: "13000",
    description: "Recruitment agency.",
    documents: {
      commercialRegister: { filename: "RC_QuickHire.pdf", url: "/docs/rc8.pdf", uploadedAt: new Date("2026-01-05") },
      nifDocument: { filename: "NIF_QuickHire.pdf", url: "/docs/nif8.pdf", uploadedAt: new Date("2026-01-05") },
    },
    adminFullName: "Omar Ziani",
    adminEmail: "omar@quickhire.dz",
    status: "Rejected",
    registrationDate: new Date("2026-01-05"),
    jobOffersCount: 0,
    totalApplications: 0,
    acceptedCandidates: 0,
    createdAt: new Date("2026-01-05"),
    updatedAt: new Date("2026-01-08"),
  },
];

// ── Platform-wide Candidates ──
export const mockAdminCandidates: Candidate[] = [
  {
    id: "u1", firstName: "John", lastName: "Doe", email: "john@example.dz", phoneNumber: "+213 555 111 222",
    wilaya: "Algiers", postalCode: "16000", educationLevel: "Master's Degree", fieldOfStudy: "IT & Software",
    university: "USTHB", graduationYear: 2019, yearsOfExperience: "5-10 years",
    currentPosition: "Senior Developer", currentCompany: "Freelance",
    skills: ["PHP", "Laravel", "MySQL", "Docker", "React"], languages: [{ name: "Arabic", level: "Native" }, { name: "French", level: "Fluent" }],
    createdAt: new Date("2025-12-01"), updatedAt: new Date("2026-02-10"),
  },
  {
    id: "u2", firstName: "Amina", lastName: "Khelif", email: "amina@example.dz", phoneNumber: "+213 555 222 333",
    wilaya: "Oran", postalCode: "31000", educationLevel: "Master's Degree", fieldOfStudy: "IT & Software",
    university: "USTO", graduationYear: 2018, yearsOfExperience: "5-10 years",
    currentPosition: "Backend Lead", currentCompany: "WebAgency DZ",
    skills: ["PHP", "Symfony", "PostgreSQL", "Redis", "Vue.js"], languages: [{ name: "Arabic", level: "Native" }, { name: "French", level: "Fluent" }],
    createdAt: new Date("2025-12-05"), updatedAt: new Date("2026-01-22"),
  },
  {
    id: "u3", firstName: "Youcef", lastName: "Mebarki", email: "youcef@example.dz", phoneNumber: "+213 555 333 444",
    wilaya: "Constantine", postalCode: "25000", educationLevel: "Bachelor's Degree", fieldOfStudy: "IT & Software",
    university: "Université Constantine 1", graduationYear: 2021, yearsOfExperience: "2-5 years",
    skills: ["PHP", "Laravel", "MySQL", "JavaScript"], languages: [{ name: "Arabic", level: "Native" }, { name: "French", level: "Fluent" }],
    createdAt: new Date("2025-12-10"), updatedAt: new Date("2026-01-28"),
  },
  {
    id: "u4", firstName: "Fatima Zohra", lastName: "Boudiaf", email: "fatima@example.dz", phoneNumber: "+213 555 444 555",
    wilaya: "Algiers", postalCode: "16000", educationLevel: "Bachelor's Degree", fieldOfStudy: "IT & Software",
    university: "ESI", graduationYear: 2023, yearsOfExperience: "0-1 years (Entry Level)",
    skills: ["PHP", "HTML", "CSS", "JavaScript"], languages: [{ name: "Arabic", level: "Native" }, { name: "French", level: "Fluent" }, { name: "English", level: "Intermediate" }],
    createdAt: new Date("2026-01-15"), updatedAt: new Date("2026-02-01"),
  },
  {
    id: "u6", firstName: "Sara", lastName: "Benattia", email: "sara@example.dz", phoneNumber: "+213 555 666 777",
    wilaya: "Algiers", postalCode: "16000", educationLevel: "Master's Degree", fieldOfStudy: "IT & Software",
    university: "ESI", graduationYear: 2020, yearsOfExperience: "2-5 years",
    currentPosition: "Full Stack Dev", currentCompany: "StartupDZ",
    skills: ["React", "Node.js", "TypeScript", "MongoDB", "Next.js"], languages: [{ name: "Arabic", level: "Native" }, { name: "French", level: "Fluent" }, { name: "English", level: "Fluent" }],
    createdAt: new Date("2026-01-20"), updatedAt: new Date("2026-02-06"),
  },
  {
    id: "u7", firstName: "Mohamed", lastName: "Cherif", email: "mohamed@example.dz", phoneNumber: "+213 555 777 888",
    wilaya: "Blida", postalCode: "09000", educationLevel: "Bachelor's Degree", fieldOfStudy: "IT & Software",
    university: "Université Blida 1", graduationYear: 2021, yearsOfExperience: "2-5 years",
    skills: ["React", "Node.js", "PostgreSQL", "Docker"], languages: [{ name: "Arabic", level: "Native" }, { name: "French", level: "Fluent" }],
    createdAt: new Date("2026-01-25"), updatedAt: new Date("2026-02-07"),
  },
  {
    id: "u8", firstName: "Nadia", lastName: "Touati", email: "nadia.t@example.dz", phoneNumber: "+213 555 888 999",
    wilaya: "Sétif", postalCode: "19000", educationLevel: "Master's Degree", fieldOfStudy: "Healthcare",
    university: "Université Sétif 1", graduationYear: 2020, yearsOfExperience: "2-5 years",
    skills: ["Data Analysis", "Python", "R", "SQL", "Tableau"], languages: [{ name: "Arabic", level: "Native" }, { name: "French", level: "Fluent" }],
    createdAt: new Date("2026-02-01"), updatedAt: new Date("2026-02-10"),
  },
  {
    id: "u9", firstName: "Amine", lastName: "Belkacem", email: "amine.b@example.dz", phoneNumber: "+213 555 999 000",
    wilaya: "Tizi Ouzou", postalCode: "15000", educationLevel: "Bachelor's Degree", fieldOfStudy: "IT & Software",
    university: "Université Mouloud Mammeri", graduationYear: 2022, yearsOfExperience: "0-1 years (Entry Level)",
    skills: ["JavaScript", "React", "CSS"], languages: [{ name: "Tamazight", level: "Native" }, { name: "French", level: "Fluent" }, { name: "Arabic", level: "Fluent" }],
    createdAt: new Date("2026-02-05"), updatedAt: new Date("2026-02-11"),
  },
];

// ── Platform Analytics Data ──
export const platformStats = {
  totalCompanies: 8,
  approvedCompanies: 5,
  pendingCompanies: 2,
  rejectedCompanies: 1,
  totalCandidates: 8,
  totalJobOffers: 6,
  activeJobOffers: 6,
  closedJobOffers: 0,
  totalApplications: 110,
  pendingApplications: 42,
  acceptedApplications: 38,
  rejectedApplications: 30,
};

export const monthlyRegistrations = [
  { month: "Sep", companies: 1, candidates: 0 },
  { month: "Oct", companies: 1, candidates: 0 },
  { month: "Nov", companies: 1, candidates: 0 },
  { month: "Dec", companies: 0, candidates: 3 },
  { month: "Jan", companies: 1, candidates: 3 },
  { month: "Feb", companies: 1, candidates: 2 },
];

export const applicationsByDomain = [
  { domain: "IT & Software", count: 65 },
  { domain: "Marketing", count: 15 },
  { domain: "Healthcare", count: 10 },
  { domain: "Education", count: 12 },
  { domain: "Finance", count: 8 },
];

// ── Platform Users (all roles) ──
type AdminUser = {
  id: string;
  name: string;
  email: string;
  role: "admin" | "candidate" | "company";
  status: "Active" | "Pending" | "Suspended";
  createdAt: Date;
};

export const mockAdminUsers: AdminUser[] = [
  { id: "admin1", name: "Super Admin", email: "admin@cvision.dz", role: "admin" as const, status: "Active" as const, createdAt: new Date("2025-01-01") },
  { id: "u1", name: "John Doe", email: "john@example.dz", role: "candidate" as const, status: "Active" as const, createdAt: new Date("2025-12-01") },
  { id: "u2", name: "Amina Khelif", email: "amina@example.dz", role: "candidate" as const, status: "Active" as const, createdAt: new Date("2025-12-05") },
  { id: "u3", name: "Youcef Mebarki", email: "youcef@example.dz", role: "candidate" as const, status: "Active" as const, createdAt: new Date("2025-12-10") },
  { id: "u4", name: "Fatima Zohra Boudiaf", email: "fatima@example.dz", role: "candidate" as const, status: "Active" as const, createdAt: new Date("2026-01-15") },
  { id: "c1-admin", name: "Ahmed Benali", email: "ahmed@techsolutions.dz", role: "company" as const, status: "Active" as const, createdAt: new Date("2025-06-15") },
  { id: "c2-admin", name: "Karima Mansouri", email: "karima@digitalmarketingdz.com", role: "company" as const, status: "Active" as const, createdAt: new Date("2025-08-10") },
  { id: "c6-admin", name: "Rachid Ferhat", email: "rachid@buildpro.dz", role: "company" as const, status: "Pending" as const, createdAt: new Date("2026-02-10") },
  { id: "c8-admin", name: "Omar Ziani", email: "omar@quickhire.dz", role: "company" as const, status: "Suspended" as const, createdAt: new Date("2026-01-05") },
];
