import type { Application } from "@/types";

export const mockApplications: Application[] = [
  {
    id: "a1",
    candidateId: "u1",
    candidateName: "John Doe",
    jobId: "1",
    jobTitle: "Senior PHP Developer",
    companyId: "c1",
    companyName: "Tech Solutions Inc.",
    appliedDate: new Date("2026-01-20"),
    currentStatus: "Accepted",
    compatibilityScore: 88,
    testStatus: "Passed",
    testScore: 88,
    testCompletedAt: new Date("2026-01-22"),
    decision: "Accept",
    decisionDate: new Date("2026-01-25"),
    comments: "Strong candidate with excellent PHP skills.",
    createdAt: new Date("2026-01-20"),
    updatedAt: new Date("2026-01-25"),
  },
  {
    id: "a2",
    candidateId: "u1",
    candidateName: "John Doe",
    jobId: "3",
    jobTitle: "Full Stack Developer",
    companyId: "c1",
    companyName: "Tech Solutions Inc.",
    appliedDate: new Date("2026-02-01"),
    currentStatus: "Pending",
    compatibilityScore: 92,
    testStatus: "Completed",
    testScore: 76,
    testCompletedAt: new Date("2026-02-03"),
    createdAt: new Date("2026-02-01"),
    updatedAt: new Date("2026-02-03"),
  },
  {
    id: "a3",
    candidateId: "u1",
    candidateName: "John Doe",
    jobId: "5",
    jobTitle: "Frontend Developer (React)",
    companyId: "c4",
    companyName: "EduTech Algeria",
    appliedDate: new Date("2026-02-08"),
    currentStatus: "Pending",
    compatibilityScore: 85,
    testStatus: "Not Started",
    createdAt: new Date("2026-02-08"),
    updatedAt: new Date("2026-02-08"),
  },
  {
    id: "a4",
    candidateId: "u1",
    candidateName: "John Doe",
    jobId: "2",
    jobTitle: "Marketing Manager",
    companyId: "c2",
    companyName: "Digital Marketing DZ",
    appliedDate: new Date("2026-01-15"),
    currentStatus: "Rejected",
    compatibilityScore: 72,
    decision: "Reject",
    decisionDate: new Date("2026-01-20"),
    comments: "Profile doesn't match the marketing requirements.",
    createdAt: new Date("2026-01-15"),
    updatedAt: new Date("2026-01-20"),
  },
  {
    id: "a5",
    candidateId: "u1",
    candidateName: "John Doe",
    jobId: "6",
    jobTitle: "Financial Analyst",
    companyId: "c5",
    companyName: "FinanceAlgeria",
    appliedDate: new Date("2026-02-10"),
    currentStatus: "Pending",
    compatibilityScore: 58,
    testStatus: "Not Started",
    createdAt: new Date("2026-02-10"),
    updatedAt: new Date("2026-02-10"),
  },
];
