import type { Company, Application } from "@/types";

export const mockCompany: Company = {
  id: "c1",
  companyName: "Tech Solutions Inc.",
  activityDomain: "IT & Software",
  professionalEmail: "contact@techsolutions.dz",
  phoneNumber: "+213 555 123 456",
  website: "https://techsolutions.dz",
  wilaya: "Algiers",
  postalCode: "16000",
  description:
    "Tech Solutions Inc. is a leading software development company based in Algiers. We specialize in building scalable web and mobile applications for businesses across Algeria and North Africa. Our team of 50+ engineers delivers cutting-edge solutions in e-commerce, fintech, and enterprise software.",
  documents: {
    commercialRegister: {
      filename: "RC_TechSolutions_2025.pdf",
      url: "/docs/rc.pdf",
      uploadedAt: new Date("2025-06-15"),
    },
    nifDocument: {
      filename: "NIF_TechSolutions.pdf",
      url: "/docs/nif.pdf",
      uploadedAt: new Date("2025-06-15"),
    },
  },
  adminFullName: "Ahmed Benali",
  adminEmail: "ahmed@techsolutions.dz",
  status: "Approved",
  registrationDate: new Date("2025-06-15"),
  approvedDate: new Date("2025-06-18"),
  approvedBy: "admin1",
  jobOffersCount: 3,
  totalApplications: 18,
  acceptedCandidates: 5,
  createdAt: new Date("2025-06-15"),
  updatedAt: new Date("2026-02-10"),
};

// Applications from multiple candidates to company c1's jobs
export const mockCompanyApplications: Application[] = [
  // Job 1 - Senior PHP Developer (45 applications, showing top ones)
  {
    id: "ca1",
    candidateId: "u1",
    candidateName: "John Doe",
    jobId: "1",
    jobTitle: "Senior PHP Developer",
    companyId: "c1",
    companyName: "Tech Solutions Inc.",
    appliedDate: new Date("2026-01-20"),
    currentStatus: "Accepted",
    compatibilityScore: 88,
    testStatus: "Passed",
    testScore: 88,
    testCompletedAt: new Date("2026-01-22"),
    decision: "Accept",
    decisionDate: new Date("2026-01-25"),
    comments: "Strong candidate with excellent PHP skills.",
    createdAt: new Date("2026-01-20"),
    updatedAt: new Date("2026-01-25"),
  },
  {
    id: "ca2",
    candidateId: "u2",
    candidateName: "Amina Khelif",
    jobId: "1",
    jobTitle: "Senior PHP Developer",
    companyId: "c1",
    companyName: "Tech Solutions Inc.",
    appliedDate: new Date("2026-01-22"),
    currentStatus: "Accepted",
    compatibilityScore: 92,
    testStatus: "Passed",
    testScore: 95,
    testCompletedAt: new Date("2026-01-24"),
    decision: "Accept",
    decisionDate: new Date("2026-01-26"),
    comments: "Exceptional skills and experience.",
    createdAt: new Date("2026-01-22"),
    updatedAt: new Date("2026-01-26"),
  },
  {
    id: "ca3",
    candidateId: "u3",
    candidateName: "Youcef Mebarki",
    jobId: "1",
    jobTitle: "Senior PHP Developer",
    companyId: "c1",
    companyName: "Tech Solutions Inc.",
    appliedDate: new Date("2026-01-25"),
    currentStatus: "Pending",
    compatibilityScore: 78,
    testStatus: "Passed",
    testScore: 72,
    testCompletedAt: new Date("2026-01-28"),
    createdAt: new Date("2026-01-25"),
    updatedAt: new Date("2026-01-28"),
  },
  {
    id: "ca4",
    candidateId: "u4",
    candidateName: "Fatima Zohra Boudiaf",
    jobId: "1",
    jobTitle: "Senior PHP Developer",
    companyId: "c1",
    companyName: "Tech Solutions Inc.",
    appliedDate: new Date("2026-02-01"),
    currentStatus: "Pending",
    compatibilityScore: 70,
    testStatus: "Not Started",
    createdAt: new Date("2026-02-01"),
    updatedAt: new Date("2026-02-01"),
  },
  {
    id: "ca5",
    candidateId: "u5",
    candidateName: "Karim Hadj",
    jobId: "1",
    jobTitle: "Senior PHP Developer",
    companyId: "c1",
    companyName: "Tech Solutions Inc.",
    appliedDate: new Date("2026-02-03"),
    currentStatus: "Rejected",
    compatibilityScore: 45,
    testStatus: "Failed",
    testScore: 40,
    testCompletedAt: new Date("2026-02-04"),
    decision: "Reject",
    decisionDate: new Date("2026-02-05"),
    comments: "Test score below passing threshold.",
    createdAt: new Date("2026-02-03"),
    updatedAt: new Date("2026-02-05"),
  },
  // Job 3 - Full Stack Developer
  {
    id: "ca7",
    candidateId: "u6",
    candidateName: "Sara Benattia",
    jobId: "3",
    jobTitle: "Full Stack Developer",
    companyId: "c1",
    companyName: "Tech Solutions Inc.",
    appliedDate: new Date("2026-02-05"),
    currentStatus: "Accepted",
    compatibilityScore: 95,
    testStatus: "Passed",
    testScore: 90,
    testCompletedAt: new Date("2026-02-06"),
    decision: "Accept",
    decisionDate: new Date("2026-02-08"),
    comments: "Outstanding full stack profile.",
    createdAt: new Date("2026-02-05"),
    updatedAt: new Date("2026-02-08"),
  },
  {
    id: "ca8",
    candidateId: "u7",
    candidateName: "Mohamed Cherif",
    jobId: "3",
    jobTitle: "Full Stack Developer",
    companyId: "c1",
    companyName: "Tech Solutions Inc.",
    appliedDate: new Date("2026-02-06"),
    currentStatus: "Accepted",
    compatibilityScore: 85,
    testStatus: "Passed",
    testScore: 82,
    testCompletedAt: new Date("2026-02-07"),
    decision: "Accept",
    decisionDate: new Date("2026-02-09"),
    createdAt: new Date("2026-02-06"),
    updatedAt: new Date("2026-02-09"),
  },
  {
    id: "ca9",
    candidateId: "u8",
    candidateName: "Nadia Touati",
    jobId: "3",
    jobTitle: "Full Stack Developer",
    companyId: "c1",
    companyName: "Tech Solutions Inc.",
    appliedDate: new Date("2026-02-08"),
    currentStatus: "Pending",
    compatibilityScore: 80,
    testStatus: "Passed",
    testScore: 68,
    testCompletedAt: new Date("2026-02-10"),
    createdAt: new Date("2026-02-08"),
    updatedAt: new Date("2026-02-10"),
  },
  {
    id: "ca10",
    candidateId: "u9",
    candidateName: "Amine Belkacem",
    jobId: "3",
    jobTitle: "Full Stack Developer",
    companyId: "c1",
    companyName: "Tech Solutions Inc.",
    appliedDate: new Date("2026-02-10"),
    currentStatus: "Rejected",
    compatibilityScore: 55,
    testStatus: "Failed",
    testScore: 35,
    testCompletedAt: new Date("2026-02-11"),
    decision: "Reject",
    decisionDate: new Date("2026-02-12"),
    comments: "Insufficient test performance.",
    createdAt: new Date("2026-02-10"),
    updatedAt: new Date("2026-02-12"),
  },
  // Additional recent applications
  {
    id: "ca11",
    candidateId: "u10",
    candidateName: "Lina Messaoudi",
    jobId: "1",
    jobTitle: "Senior PHP Developer",
    companyId: "c1",
    companyName: "Tech Solutions Inc.",
    appliedDate: new Date("2026-02-12"),
    currentStatus: "Pending",
    compatibilityScore: 82,
    testStatus: "Not Started",
    createdAt: new Date("2026-02-12"),
    updatedAt: new Date("2026-02-12"),
  },
  {
    id: "ca12",
    candidateId: "u11",
    candidateName: "Reda Bouzid",
    jobId: "3",
    jobTitle: "Full Stack Developer",
    companyId: "c1",
    companyName: "Tech Solutions Inc.",
    appliedDate: new Date("2026-02-13"),
    currentStatus: "Pending",
    compatibilityScore: 74,
    testStatus: "Not Started",
    createdAt: new Date("2026-02-13"),
    updatedAt: new Date("2026-02-13"),
  },
];
