import type { JobOffer } from "@/types";

export const mockJobs: JobOffer[] = [
  {
    id: "1",
    companyId: "c1",
    companyName: "Tech Solutions Inc.",
    companyLogo: undefined,
    jobTitle: "Senior PHP Developer",
    jobDescription:
      "We are looking for an experienced PHP developer to join our backend team. You will work on large-scale web applications serving thousands of users across Algeria.",
    requirements: [
      "5+ years of PHP experience",
      "Strong knowledge of Laravel framework",
      "Experience with MySQL and PostgreSQL",
      "Understanding of RESTful APIs",
      "Familiarity with Git and CI/CD",
    ],
    responsibilities: [
      "Develop and maintain backend services",
      "Write clean, testable, and efficient code",
      "Participate in code reviews",
      "Collaborate with frontend developers",
      "Optimize application performance",
    ],
    contractType: "CDI",
    domain: "IT & Software",
    wilaya: "Algiers",
    postalCode: "16000",
    salaryRange: "100,000 - 200,000 DA",
    experienceRequired: "5-10 years",
    maxAcceptedCandidates: 5,
    currentAccepted: 2,
    requireQCMTest: true,
    linkedTestId: "t1",
    status: "Active",
    postedDate: new Date("2026-02-01"),
    applicationsCount: 45,
    matchPercentage: 88,
    saved: false,
    createdAt: new Date("2026-02-01"),
    updatedAt: new Date("2026-02-01"),
  },
  {
    id: "2",
    companyId: "c2",
    companyName: "Digital Marketing DZ",
    jobTitle: "Marketing Manager",
    jobDescription:
      "Lead our marketing team and develop strategies to grow brand awareness in the Algerian market. Experience with digital campaigns is essential.",
    requirements: [
      "3+ years in marketing management",
      "Strong analytical skills",
      "Experience with digital marketing tools",
      "Excellent communication in Arabic and French",
    ],
    responsibilities: [
      "Develop and execute marketing strategies",
      "Manage social media campaigns",
      "Analyze market trends and competitors",
      "Manage the marketing budget",
    ],
    contractType: "CDI",
    domain: "Marketing",
    wilaya: "Oran",
    postalCode: "31000",
    salaryRange: "100,000 - 200,000 DA",
    experienceRequired: "2-5 years",
    maxAcceptedCandidates: 3,
    currentAccepted: 0,
    requireQCMTest: false,
    status: "Active",
    postedDate: new Date("2026-02-05"),
    applicationsCount: 32,
    matchPercentage: 72,
    saved: true,
    createdAt: new Date("2026-02-05"),
    updatedAt: new Date("2026-02-05"),
  },
  {
    id: "3",
    companyId: "c1",
    companyName: "Tech Solutions Inc.",
    jobTitle: "Full Stack Developer",
    jobDescription:
      "Join our agile team to build modern web applications using React and Node.js. We value clean code, collaboration, and continuous learning.",
    requirements: [
      "3+ years full stack experience",
      "Proficiency in React and Node.js",
      "Experience with TypeScript",
      "Knowledge of cloud services (AWS/GCP)",
    ],
    responsibilities: [
      "Build responsive frontend interfaces",
      "Develop and maintain APIs",
      "Write unit and integration tests",
      "Deploy and monitor applications",
    ],
    contractType: "CDI",
    domain: "IT & Software",
    wilaya: "Algiers",
    postalCode: "16000",
    salaryRange: "100,000 - 200,000 DA",
    experienceRequired: "2-5 years",
    maxAcceptedCandidates: 5,
    currentAccepted: 3,
    requireQCMTest: true,
    linkedTestId: "t2",
    status: "Active",
    postedDate: new Date("2026-02-08"),
    applicationsCount: 58,
    matchPercentage: 92,
    saved: false,
    createdAt: new Date("2026-02-08"),
    updatedAt: new Date("2026-02-08"),
  },
  {
    id: "4",
    companyId: "c3",
    companyName: "HealthCare Plus",
    jobTitle: "Medical Data Analyst",
    jobDescription:
      "Analyze healthcare data to improve patient outcomes and operational efficiency in our network of clinics across Algeria.",
    requirements: [
      "Degree in Data Science or Healthcare",
      "Experience with data analysis tools",
      "Knowledge of healthcare systems",
      "Strong presentation skills",
    ],
    responsibilities: [
      "Collect and analyze healthcare data",
      "Create reports and dashboards",
      "Present insights to stakeholders",
      "Identify trends and opportunities",
    ],
    contractType: "CDD",
    domain: "Healthcare",
    wilaya: "Constantine",
    postalCode: "25000",
    salaryRange: "50,000 - 100,000 DA",
    experienceRequired: "0-1 years (Entry Level)",
    maxAcceptedCandidates: 2,
    currentAccepted: 0,
    requireQCMTest: false,
    status: "Active",
    postedDate: new Date("2026-02-10"),
    applicationsCount: 18,
    matchPercentage: 65,
    saved: false,
    createdAt: new Date("2026-02-10"),
    updatedAt: new Date("2026-02-10"),
  },
  {
    id: "5",
    companyId: "c4",
    companyName: "EduTech Algeria",
    jobTitle: "Frontend Developer (React)",
    jobDescription:
      "Build beautiful, accessible interfaces for our e-learning platform serving students across Algeria.",
    requirements: [
      "2+ years React experience",
      "Strong CSS/Tailwind skills",
      "Experience with Next.js",
      "Eye for design and UX",
    ],
    responsibilities: [
      "Implement UI designs with pixel precision",
      "Ensure accessibility standards",
      "Optimize performance and loading times",
      "Collaborate with designers and backend team",
    ],
    contractType: "CDI",
    domain: "Education",
    wilaya: "Sétif",
    postalCode: "19000",
    salaryRange: "50,000 - 100,000 DA",
    experienceRequired: "2-5 years",
    maxAcceptedCandidates: 4,
    currentAccepted: 1,
    requireQCMTest: true,
    linkedTestId: "t3",
    status: "Active",
    postedDate: new Date("2026-02-12"),
    applicationsCount: 27,
    matchPercentage: 85,
    saved: false,
    createdAt: new Date("2026-02-12"),
    updatedAt: new Date("2026-02-12"),
  },
  {
    id: "6",
    companyId: "c5",
    companyName: "FinanceAlgeria",
    jobTitle: "Financial Analyst",
    jobDescription:
      "Perform financial analysis and reporting for one of Algeria's fastest growing fintech companies.",
    requirements: [
      "Degree in Finance or Accounting",
      "2+ years financial analysis",
      "Advanced Excel and financial modeling",
      "Knowledge of Algerian tax regulations",
    ],
    responsibilities: [
      "Prepare financial reports and forecasts",
      "Analyze investment opportunities",
      "Monitor market trends",
      "Support management in decision making",
    ],
    contractType: "CDI",
    domain: "Finance",
    wilaya: "Algiers",
    postalCode: "16000",
    salaryRange: "100,000 - 200,000 DA",
    experienceRequired: "2-5 years",
    maxAcceptedCandidates: 2,
    currentAccepted: 0,
    requireQCMTest: true,
    linkedTestId: "t4",
    status: "Active",
    postedDate: new Date("2026-02-14"),
    applicationsCount: 15,
    matchPercentage: 58,
    saved: false,
    createdAt: new Date("2026-02-14"),
    updatedAt: new Date("2026-02-14"),
  },
];
